{{- if .Values.clickhouse.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ include "clickhouse.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules: 
  - host: {{ .Values.clickhouse.ingress.host }}
    http: 
      paths: 
      - path: {{ .Values.clickhouse.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "clickhouse.fullname" . }}
            port:
              number: 8123
{{- if .Values.clickhouse.ingress.tls.enabled }}
  tls: 
  - hosts: 
    {{- range .Values.clickhouse.ingress.tls.hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .Values.clickhouse.ingress.tls.secretName }}
{{- end }}
{{- end }}
